version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: dev
      DB_USERNAME: admin
      DB_PASSWORD: password
      SECRET_KEY: VNLNRanking-Backend-Testing
      LOG_DIR: ./logs
      PORT: 3000
      HCAPTCHA_SECRET: '0x0000000000000000000000000000000000000000'  # Test secret for development
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_DATABASE: dev
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
